'use client';
import Link from 'next/link';
import CompanyBrand from '@/components/CompanyBrand';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Eye,EyeOff,LockKeyhole,ShieldCheck} from 'lucide-react';
export default function Login(){
 const [password,setPassword]=useState('');const [visible,setVisible]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function login(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/admin/verify-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({panelPassword:password})});const data=await r.json();if(!r.ok)throw new Error(data.message||'Unable to sign in.');window.location.assign('/admin')}catch(e){setError(e instanceof Error?e.message:'Unable to connect. Please try again.');setBusy(false)}}
 return <main className="loginPage"><section className="loginStory"><CompanyBrand/><div><span className="eyebrow">YOUR PEOPLE. YOUR WORKSPACE.</span><h1>A little more clarity.<br/>Every workday.</h1><p>People, attendance and everyday operations. Together in one thoughtfully simple workspace.</p><div className="loginStoryStats"><div><strong>One place</strong><span>for your whole team</span></div><div><strong>Every day</strong><span>a clearer overview</span></div></div></div><span className="storyFooter">Made for teams on the move.</span></section><section className="loginFormSection"><Link href="/" className="backLink"><ArrowLeft size={16}/> Employee portal</Link><form onSubmit={login} className="loginForm"><span className="featureIcon"><LockKeyhole size={26}/></span><p className="eyebrow">ADMIN WORKSPACE</p><h1>Welcome back.</h1><p className="muted">Enter your admin password to open your workspace.</p><label htmlFor="admin-password">Admin password</label><div className="passwordField"><input id="admin-password" className="input" type={visible?'text':'password'} autoComplete="current-password" required autoFocus value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button className="iconButton" type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(x=>!x)}>{visible?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{error&&<p role="alert" className="flowMessage">{error}</p>}<button className="btn primary loginSubmit" disabled={busy}>{busy?'Opening workspace…':'Open workspace'}<ArrowRight size={18}/></button><p className="loginNote"><ShieldCheck size={16}/> Secure administrator access</p></form><span className="loginCopyright">Attendance Pro · People first, always.</span></section></main>;
}
