const test=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const vm=require('node:vm');const XLSX=require('xlsx');
function route(rows=[],authorized=true){const exports={};const time={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/time.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:time,require});let filtered=rows;const query={select(){return this},gte(key,value){filtered=filtered.filter(row=>row[key]>=value);return this},lte(key,value){filtered=filtered.filter(row=>row[key]<=value);return this},order(){return this},eq(key,value){filtered=filtered.filter(row=>row[key]===value);return this},async range(start,end){return {data:filtered.slice(start,end+1)}}};const mocks={'@/lib/auth':{requireAdmin:async()=>({ok:authorized,status:401})},'@/lib/supabase':{supabaseAdmin:()=>({from:()=>query})},'@/lib/time':time};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/reports/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,require:n=>mocks[n]||require(n),URL,Blob,Buffer,Uint8Array});return params=>exports.GET(new Request('http://localhost/api/reports?'+new URLSearchParams({...{from:'2026-09-01',to:'2026-09-15'},...Object.fromEntries(new URLSearchParams(params))})));}
const row={attendance_date:'2026-09-15',employees:{employee_id:'EMP01',full_name:'Test Employee',department:'Operations',designation:'Coordinator'},check_in:'2026-09-15T03:30:00Z',check_out:null,worked_minutes:null,status:'present',penalty:false};
test('reports require admin and reject invalid ranges',async()=>{assert.equal((await route([],false)('format=xls')).status,401);assert.equal((await route()('from=bad&format=pdf')).status,400);const r=await route()('to=2026-02-30');assert.equal(r.status,400);});
test('reports paginate beyond the database page size',async()=>{const response=await route(Array.from({length:1005},()=>row))('format=json');assert.equal((await response.json()).count,1005)});
for(const format of ['xls','xlsx'])test(`${format} is a real readable workbook with employee and IST times`,async()=>{const response=await route([row])('format='+format);assert.equal(response.status,200);const bytes=Buffer.from(await response.arrayBuffer());if(format==='xls')assert.equal(bytes.subarray(0,4).toString('hex'),'d0cf11e0');const workbook=XLSX.read(bytes);const data=XLSX.utils.sheet_to_json(workbook.Sheets.Attendance);assert.equal(data[0].Name,'Test Employee');assert.match(data[0]['Check In (IST)'],/9:00:00/);});
test('PDF export generates a PDF document',async()=>{const response=await route(Array.from({length:25},()=>row))('format=pdf');assert.equal(response.status,200);const bytes=Buffer.from(await response.arrayBuffer());assert.equal(bytes.subarray(0,4).toString(),'%PDF');});

test('employee and custom date filters apply together',async()=>{const response=await route([{...row,employee_id:'one'},{...row,employee_id:'two'},{...row,employee_id:'one',attendance_date:'2026-08-31'}])('employeeId=one');const data=await response.json();assert.equal(data.count,1);assert.equal(data.rows[0].employee_id,'one');});
test('full day excludes incomplete shifts, absences and half days, including completed late shifts',async()=>{const records=[row,{...row,check_out:'2026-09-15T12:30:00Z'},{...row,status:'late',check_out:'2026-09-15T13:30:00Z'},{...row,status:'half_day',check_out:'2026-09-15T07:30:00Z'},{...row,status:'absent',check_in:null}];const full=await (await route(records)('status=full_day')).json();assert.equal(full.count,2);assert.deepEqual(full.rows.map(row=>row.status),['present','late']);for(const status of ['absent','half_day']){const result=await (await route(records)('status='+status)).json();assert.equal(result.count,1);assert.equal(result.rows[0].status,status);}});
test('employee and full-day filters are preserved in Excel downloads',async()=>{const response=await route([{...row,employee_id:'one',check_out:'2026-09-15T12:30:00Z'},{...row,employee_id:'two',check_out:'2026-09-15T12:30:00Z'},{...row,employee_id:'one'}])('employeeId=one&status=full_day&format=xls');const workbook=XLSX.read(Buffer.from(await response.arrayBuffer()));assert.equal(XLSX.utils.sheet_to_json(workbook.Sheets.Attendance).length,1);});
