import Link from 'next/link';
import {redirect,notFound} from 'next/navigation';
import {ArrowLeft,FileText,ArrowUpRight,UserRound,CalendarClock} from 'lucide-react';
import {z} from 'zod';
import {requireAdmin} from '@/lib/auth';
import {supabaseAdmin} from '@/lib/supabase';
import {istDateTime,hoursLabel} from '@/lib/time';
type Document={name:string;size?:number;uploadedAt?:string;path:string};
export default async function EmployeeDetail({params}:{params:Promise<{employeeId:string}>}){
 if(!(await requireAdmin()).ok)redirect('/admin/login');
 const {employeeId}=await params;if(!z.string().uuid().safeParse(employeeId).success)notFound();
 const s=supabaseAdmin();const {data:employee,error}=await s.from('employees').select('*').eq('id',employeeId).maybeSingle();
 if(error)throw new Error('Unable to load employee details.');if(!employee)notFound();
 const {data:attendance,error:attendanceError}=await s.from('attendance').select('id,attendance_date,check_in,check_out,worked_minutes,status').eq('employee_id',employeeId).order('attendance_date',{ascending:false}).limit(10);
 const documents:Document[]=Array.isArray(employee.documents)?employee.documents:[];
 const details=[['Employee ID',employee.employee_id],['Full name',employee.full_name],['Mobile number',employee.mobile],['Emergency number',employee.emergency_phone],['Email',employee.email],['Gender',employee.gender],['Date of birth',employee.date_of_birth],['Department',employee.department],['Designation',employee.designation],['Date of joining',employee.date_of_joining],['Shift start',employee.shift_start?.slice(0,5)],['Shift end',employee.shift_end?.slice(0,5)],['Total hours',employee.standard_hours],['Status',employee.status]];
 return <div className="container"><Link className="backLink" href="/admin/employees"><ArrowLeft size={16}/> All employees</Link><div className="detailHero"><span className="featureIcon"><UserRound size={28}/></span><div><p className="eyebrow">EMPLOYEE PROFILE</p><h1>{employee.full_name}</h1><p className="muted">{employee.employee_id} · {employee.department||'No department'} · {employee.designation||'Employee'}</p></div><span className="statusPill ready">{employee.status}</span></div><div className="grid grid2"><section className="card"><h2>Personal & employment details</h2><dl className="detailGrid">{details.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl></section><section className="card"><div className="sectionHeading"><h2>Employee documents</h2><span className="countBadge">{documents.length}</span></div><p className="muted">Files uploaded for this employee.</p><div className="documentList">{documents.map((doc,index)=><a className="documentItem" key={doc.path} href={`/api/admin/media?kind=document&id=${employeeId}&index=${index}`} target="_blank" rel="noopener noreferrer"><FileText size={23}/><div><strong>{doc.name}</strong><small>{doc.size?`${Math.ceil(doc.size/1024)} KB`:'Document'}{doc.uploadedAt?` · ${istDateTime(doc.uploadedAt)} IST`:''}</small></div><ArrowUpRight size={18}/></a>)}</div>{!documents.length&&<div className="emptyState"><FileText size={30}/><p>No documents uploaded yet.</p></div>}<Link className="btn" href="/admin/documents">Upload documents</Link></section></div><section className="card" style={{marginTop:24}}><div className="sectionHeading"><h2><CalendarClock size={20}/> Recent attendance</h2><span className="muted">Latest 10 records</span></div>{attendanceError?<p role="alert">Unable to load attendance. Refresh to try again.</p>:<div className="tableWrap"><table><thead><tr><th>Date</th><th>Check-in (IST)</th><th>Check-out (IST)</th><th>Worked</th><th>Status</th><th>Details</th></tr></thead><tbody>{attendance?.map(row=><tr key={row.id}><td>{row.attendance_date}</td><td>{row.check_in?istDateTime(row.check_in):'—'}</td><td>{row.check_out?istDateTime(row.check_out):'—'}</td><td>{hoursLabel(row.worked_minutes)}</td><td>{row.status.replaceAll('_',' ')}</td><td><Link className="btn small" href={'/admin/attendance/'+row.id}>View</Link></td></tr>)}</tbody></table>{!attendance?.length&&<p>No attendance recorded yet.</p>}</div>}</section></div>;
}
