'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Eye,CalendarDays,RefreshCw} from 'lucide-react';
import {todayIST,istTime,hoursLabel} from '@/lib/time';
type Row={id:string;attendance_date:string;check_in:string|null;check_out:string|null;worked_minutes:number|null;status:string;penalty:boolean;employees?:{full_name:string;employee_id:string;department?:string}};
export default function Attendance(){
 const [date,setDate]=useState(todayIST()),[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setMessage('');fetch('/api/reports?date='+date,{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.message||'Unable to load attendance.');setRows(data.rows||[])}).catch(e=>{if(!controller.signal.aborted){setMessage(e.message);setRows([])}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[date,refresh]);
 return <div className="container"><div className="pageHead"><div><p className="eyebrow">YOUR TEAM’S WORKDAY</p><h1>Attendance</h1><p className="muted">Review daily records, captured photos and attendance times in IST.</p></div><button className="btn" disabled={loading} onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={16}/> Refresh</button></div><div className="card attendanceFilter"><label><span><CalendarDays size={16}/> Attendance date</span><input className="input" type="date" required value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label><span className="statusPill ready">{loading?'Loading…':`${rows.length} records`}</span></div>{message&&<p role="alert" className="flowMessage">{message}</p>}<div className="card tableWrap" style={{marginTop:22}}><table><thead><tr><th>Employee</th><th>Employee ID</th><th>Check-in (IST)</th><th>Check-out (IST)</th><th>Worked</th><th>Status</th><th>Penalty</th><th>Details & photos</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.employees?.full_name}<small className="tableSubtext">{row.employees?.department}</small></td><td>{row.employees?.employee_id}</td><td>{row.check_in?istTime(row.check_in):'—'}</td><td>{row.check_out?istTime(row.check_out):'—'}</td><td>{hoursLabel(row.worked_minutes)}</td><td><span className={`statusPill ${row.penalty?'pending':'ready'}`}>{row.status.replaceAll('_',' ')}</span></td><td>{row.penalty?'Applied':'None'}</td><td><Link className="btn small" href={'/admin/attendance/'+row.id}><Eye size={15}/> View</Link></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="emptyState"><CalendarDays size={30}/><p>No attendance records for this date.</p></div>}</div></div>;
}
